name = "SoleModels"
uuid = "4249d9c7-3290-4ddd-961c-e1d3ec2467f8"
license = "MIT"
authors = ["Michele GHIOTTI", "Giovanni PAGLIARINI", "Edoardo PONSANESI", "Eduard I. STAN"]
version = "0.10.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
CategoricalArrays = "324d7699-5711-5eae-9e2f-1d82baa6b597"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
FillArrays = "1a297f60-69ca-5386-bcde-b61e274b549b"
FunctionWrappers = "069b7b12-0de2-55c6-9aab-29f3d0a68a2e"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SoleBase = "4475fa32-7023-44a0-aa70-4813b230e492"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
SoleLogics = "b002da8f-3cb3-4d91-bbe3-2953433912b5"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
ThreadSafeDicts = "4239201d-c60e-5e0a-9702-85d713665ba7"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[weakdeps]
DecisionTree = "7806a523-6efd-50cb-b5f6-3fa6f1930dbb"
XGBoost = "009559a3-9522-5dbb-924b-0b6ed2b22bb9"

[extensions]
DecisionTreeExt = "DecisionTree"
XGBoostExt = "XGBoost"

[compat]
AbstractTrees = "0.4"
BenchmarkTools = "1"
CSV = "0.10"
CategoricalArrays = "0.10"
DataFrames = "1"
DataStructures = "0.18"
FillArrays = "1"
FunctionWrappers = "1"
Graphs = "1.8"
HTTP = "1.9"
IterTools = "1"
Lazy = "0.15.1"
MLJ = "0.20"
MLJBase = "1.6"
MLJDecisionTreeInterface = "0.4"
MLJModelInterface = "1.8.0"
PrettyTables = "2.2"
ProgressMeter = "1"
Random = "1"
Reexport = "1"
Revise = "3"
SoleBase = "0.12"
SoleData = "0.15, 0.16"
SoleLogics = "0.11"
StatsBase = "0.30 - 0.34"
Suppressor = "0.2"
Tables = "1"
ThreadSafeDicts = "0.1"
XGBoost = "2"
ZipFile = "0.10"
julia = "1"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
MLJ = "add582a8-e3ab-11e8-2d5e-e98b27df1bc7"
MLJBase = "a7f614a8-145f-11e9-1d2a-a57a1082229d"
MLJDecisionTreeInterface = "c6f25543-311c-4c74-83dc-3ea6d1015661"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
MLJXGBoostInterface = "54119dfa-1dab-4055-a167-80440f4f7a91"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MultiData = "8cc5100c-b3d1-4f82-90cb-0ea93d317aba"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SoleData = "123f1ae1-6307-4526-ab5b-aab3a92a2b8c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "DataFrames", "Random", "MLJ", "MLJXGBoostInterface", "MultiData", "Markdown", "InteractiveUtils", "BenchmarkTools", "MLJBase", "XGBoost", "DecisionTree", "MLJDecisionTreeInterface", "SoleData"]
